#! /bin/sh

sxhkd &

# start window compositor in bg
picom -b

# start dunst notifications
dunst &

# start geoclue agent for redshift
/usr/lib/geoclue-2.0/demos/agent &

# Source Xresources (if urxvt terminal is used)
# xrdb ~/.Xresources

# set wallpaper at start
./.fehbg

# set cursor
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config active_border_color  ea0a4a

# bspwm top padding set to height of polybar
bspc config top_padding          20
bspc focus_follows_pointer       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2' state=tiled follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a QjackCtl state=floating
bspc rule -a zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Launch polybar
$HOME/.scripts/launch_polybar

# launch MPD
mpd

# For some odd reason I need to send a message to get the dunst
# service to start. :/
# notify-send "Oh, hey dude."

