#!/usr/bin/bash
LINES=30
case "$1" in
    # *.png|*.jpg|*.jpeg|*.gif|*.mkv|*.mp4) sxiv -e $(wmctrl -lx | awk '/termite.Termite/ {print $1}') -s f "$1";;
    *.png|*.jpg|*.jpeg|*.gif|*.mkv|*.mp4) mediainfo "$1";;
    *.wav|*.aiff) play "$1";;
    *.md) glow -s dark "$1";;
    *.pdf) pdftotext "$1" -;;
    *.zip|rar|*.7z) 7z l $"1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    *.zsh*|*.bash*|*.git*|*.mod) cat "$1";;
    *) highlight "$1" -0 ansi --force;;
esac
