#!/bin/bash

SEARCH_URL="https://www.google.com/search?q="
VIDEO_EXT='(avi%7Cmkv%7Cmov%7Cmp4%7Cmpg%7Cwmv)'
IMAGE_EXT='(bmp%7Cgif%7Cjpg%7Cjpeg%7Cpng%7Cpsd%7Ctif%7Ctiff)'
AUDIO_EXT='(ac3%7Cflac%7Cm4a%7Cmp3%7Cogg%7Cwav%7Cwma)'
DOCUMENT_EXT='(CBZ%7CCBR%7CCHM%7CDOC%7CDOCX%7CEPUB%7CMOBI%7CODT%7CPDF%7CRTF%7Ctxt)'
EXECUTABLE_EXT='(exe%7Capk)'
ARCHIVE_EXT='(iso%7Crar%7Ctar%7Czip%7C7z)'

SEARCH_TAIL='%20-inurl%3A(jsp%7Cpl%7Cphp%7Chtml%7Caspx%7Chtm%7Ccf%7Cshtml)%20-inurl%3A(index_of%7Clisten77%7Cmp3raid%7Cmp3toss%7Cmp3drug%7Cindex_of%7Cwallywashis)%20intitle%3A%22index.of.%22%20%20&tbs=qdr:'

search_type=$1
SEARCH_TERM="%22intext%3A${2}%22%20%20"

case $search_type in
    "video") EXT=$VIDEO_EXT;;
    "image") EXT=$IMAGE_EXT;;
    "audio") EXT=$AUDIO_EXT;;
    "document") EXT=$DOCUMENT_EXT;;
    "executable") EXT=$EXECUTABLE_EXT;;
    "archive") EXT=$ARCHIVE_EXT;;
esac

TERM=$SEARCH_URL
TERM+=$SEARCH_TERM
TERM+=$EXT
TERM+=$SEARCH_TAIL

if [ $BROWSER -eq "firefox" ]; then
    $BROWSER --new-tab $TERM
else
    $BROWSER $TERM
fi
